from site_auto.manage_exception.custom_validation